version: "3.9"
services:
  neo4j:
    image: neo4j:5
    environment:
      - NEO4J_AUTH=neo4j/neo4jpassword
      - NEO4J_dbms_memory_heap_initial__size=24g
      - NEO4J_dbms_memory_heap_max__size=48g
      - NEO4J_dbms_memory_pagecache_size=16g
    volumes: [./data/neo4j:/data, ./graph:/graph]
    ports: ["7474:7474","7687:7687"]

  qdrant:
    image: qdrant/qdrant:latest
    volumes: [./data/qdrant:/qdrant/storage]
    ports: ["6333:6333"]

  api:
    build: ./services/api-gateway
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - QDRANT_URL=http://qdrant:6333
    depends_on: [neo4j, qdrant]
    ports: ["8080:8080"]

  ethics:
    build: ./services/ethics-measurement
    environment:
      - NEO4J_URI=bolt://neo4j:7687
    depends_on: [neo4j]

  tutor:
    build: ./services/llm-assistants/tutor
    environment:
      - API_URL=http://api:8080
    depends_on: [api]

  miners-wiki:
    build: ./services/miners/wiki-miner
    environment:
      - API_URL=http://api:8080
    depends_on: [api]
